### ISSUE TITLE
Need to export a binary icon as well

### ISSUE THREAD

**Issue by nedrichards** [flathub/com.szibele.e-juice-calc#1]
I know this app exports an SVG icon but I believe you need to create some PNG icons otherwise the app center and desktops aren't picking up your icons correctly.

Examples of this on flathub are: https://github.com/flathub/com.anydesk.Anydesk/blob/49da18f155cc6b225be5de350feda4051ddfb9fb/com.anydesk.Anydesk.json#L116

(you could easily do that as a post-install block instead once the SVG was in place)

**Comment by wjt** [comment]
@rszibele any update here? The app does not show up in (eg) GNOME Software on Endless OS or Fedora, and I think it's down to this bug.

**Comment by rszibele** [comment]
I'll keep an eye on GNOME Software, to see if it appears with the PR.

**Comment by wjt** [comment]
![screenshot from 2019-01-04 14-56-29](https://user-images.githubusercontent.com/86760/50694171-11d31980-1031-11e9-9a8c-211b35c5e749.png)
![screenshot from 2019-01-04 14-56-33](https://user-images.githubusercontent.com/86760/50694172-11d31980-1031-11e9-8b05-312ab5d27786.png)

On my Endless OS system, the app now shows up but without an icon.

**Comment by ramcq** [comment]
Yeah... the PNG is in fact... blank. Because the SVG also appears to be blank. What's going on @rszibele ?! :)

**Comment by rszibele** [comment]
@ramcq Interesting, the SVG is blank when opened in GIMP but isn't blank when opened in Firefox. The SVG seemingly uses features not supported everywhere, I'll recreate it in Inkscape.

**Comment by ramcq** [comment]
I guess GIMP uses rsvg, same as the tool we are relying on in the new converter code.On 5 Jan 2019 08:31, Richard Szibele <notifications@github.com> wrote:@ramcq Interesting, the SVG is blank when opened in GIMP but isn't blank when opened in Firefox. The SVG seemingly uses features not supported everywhere, I'll recreate it in Inkscape.

**Comment by rszibele** [comment]
Should be fixed now. It shows up correctly on Flathub, Discover and GNOME Software.

**Comment by wjt** [comment]
Yep, shows up fine in GNOME Software on Endless too. Thanks!
